"""
Markdown output assembly (FR-012).

Transforms a :class:`TranscriptResult` into a well-structured Markdown
document with clear heading hierarchy, topic clusters, summaries,
action items, and uncertainty indicators.
"""

from __future__ import annotations

from .models import ActionItem, TopicCluster, UncertainFinding


class MarkdownBuilder:
    """Assembles a Markdown document from analysis results."""

    @staticmethod
    def assemble(
        meeting_title: str,
        language: str,
        topic_clusters: list[TopicCluster],
        action_items: list[ActionItem],
        uncertain_findings: list[UncertainFinding],
    ) -> str:
        """Build a complete Markdown document.

        Output language matches the detected input language.
        Structure:
            1. Meeting title
            2. Language indicator
            3. Topic clusters with summaries
            4. Action items (deduplicated, sorted)
            5. Uncertain findings (if any)

        Args:
            meeting_title: Title of the meeting.
            language: Detected primary language.
            topic_clusters: Identified topic clusters.
            action_items: Extracted action items.
            uncertain_findings: Flagged uncertain items.

        Returns:
            Markdown string.
        """
        lines: list[str] = []

        # Title
        lines.append(f"# {meeting_title}")
        lines.append("")
        lines.append(f"*Language: {language}*")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Topic Clusters
        lines.append("## Topic Clusters")
        lines.append("")

        if not topic_clusters:
            lines.append("*No topic clusters identified.*")
            lines.append("")

        for i, cluster in enumerate(topic_clusters, 1):
            lines.append(f"### {i}. {cluster.title}")
            lines.append("")
            lines.append(cluster.summary)
            lines.append("")

            # Keywords
            if cluster.keywords:
                lines.append(
                    "**Keywords:** " + ", ".join(cluster.keywords) + ""
                )
                lines.append("")

            # Confidence
            confidence_label = "✅" if cluster.confidence >= 0.7 else "⚠️"
            lines.append(
                f"*Confidence: {confidence_label} "
                f"{cluster.confidence:.0%}*"
            )

            if cluster.uncertain:
                lines.append("⚠️ *This topic is flagged as uncertain.*")

            lines.append("")
            lines.append("")

        # Action Items
        lines.append("---")
        lines.append("")
        lines.append("## Action Items")
        lines.append("")

        if not action_items:
            lines.append("*No action items identified.*")
            lines.append("")

        for i, item in enumerate(action_items, 1):
            assignee = item.assignee or "unspecified"
            deadline = item.deadline or "unspecified"

            lines.append(
                f"{i}. **{item.description}**"
            )
            lines.append(
                f"   - Assignee: `{assignee}` | "
                f"Deadline: `{deadline}`"
            )

            if item.uncertain:
                lines.append(
                    f"   - ⚠️ *Uncertain (confidence: {item.confidence:.0%})*"
                )
            else:
                lines.append(
                    f"   - Confidence: {item.confidence:.0%}"
                )
            lines.append("")

        # Uncertain Findings
        if uncertain_findings:
            lines.append("---")
            lines.append("")
            lines.append("## ⚠️ Uncertain Findings")
            lines.append("")
            lines.append(
                "The following items could not be identified with "
                "high confidence and should be manually reviewed."
            )
            lines.append("")

            for finding in uncertain_findings:
                lines.append(
                    f"- **[{finding.type.value}]** {finding.description}"
                )

            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by Meeting Transcript Analyzer*")

        return "\n".join(lines)
